from __future__ import annotations

import asyncio
import random
import re
import urllib.parse
from typing import Any, Optional

from ..http_client import HttpClient
from ..models import Finding, ScanConfig, ScanModule, Severity


WAF_SIGNATURES: dict[str, dict[str, list[str]]] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body": ["cloudflare", "ray id:", "cf-ray"],
        "status": [403, 503],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "cookies": ["awselb", "awsalb"],
        "body": ["aws", "access denied"],
        "status": [403],
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "x-akamai-transformed", "akamai-origin-hop"],
        "cookies": ["ak_bmsc", "bm_sz"],
        "body": ["access denied", "akamai"],
        "status": [403],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "body": ["incapsula", "request unsuccessful", "incident id"],
        "status": [403],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookies": ["ts", "f5avr"],
        "body": ["the requested url was rejected", "f5 networks"],
        "status": [403],
    },
    "ModSecurity": {
        "headers": [],
        "cookies": [],
        "body": ["mod_security", "modsecurity", "406 not acceptable", "not acceptable"],
        "status": [403, 406],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body": ["sucuri website firewall", "access denied - sucuri"],
        "status": [403],
    },
    "Barracuda": {
        "headers": [],
        "cookies": ["barra_counter_session"],
        "body": ["barracuda", "you have been blocked"],
        "status": [403],
    },
    "Fortinet FortiWeb": {
        "headers": ["fortiwafsid"],
        "cookies": [],
        "body": ["fortigate", "fortiwall", "this request is blocked by the website owner"],
        "status": [403],
    },
    "Wordfence": {
        "headers": [],
        "cookies": [],
        "body": ["wordfence", "generated by wordfence", "your access to this site has been limited"],
        "status": [403],
    },
    "Nginx WAF/Naxsi": {
        "headers": [],
        "cookies": [],
        "body": ["naxsi", "naxsi_sig"],
        "status": [400],
    },
    "Citrix NetScaler": {
        "headers": ["ns_af", "citrix-transaction-id"],
        "cookies": ["ns_af", "citrix_ns_id"],
        "body": ["citrix", "netscaler"],
        "status": [403],
    },
    "Varnish": {
        "headers": ["x-varnish", "via"],
        "cookies": [],
        "body": ["error 403", "varnish cache server"],
        "status": [403],
    },
}


class WAFBypass:
    def __init__(self, config: ScanConfig, client: HttpClient) -> None:
        self.config = config
        self.client = client
        self.detected_waf: Optional[str] = None

    def detect_waf_from_response(self, resp_headers: dict[str, str], resp_body: str, status_code: int) -> Optional[str]:
        headers_lower = {k.lower(): v.lower() for k, v in resp_headers.items()}
        body_lower = resp_body.lower()

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            for h in sigs.get("headers", []):
                if h.lower() in headers_lower or any(h.lower() in v for v in headers_lower.values()):
                    score += 2

            set_cookie = headers_lower.get("set-cookie", "")
            for c in sigs.get("cookies", []):
                if c.lower() in set_cookie:
                    score += 2

            for b in sigs.get("body", []):
                if b.lower() in body_lower:
                    score += 1

            if status_code in sigs.get("status", []) and score > 0:
                score += 1

            if score >= 2:
                self.detected_waf = waf_name
                return waf_name

        return None

    async def detect_waf(self, base_url: str) -> Optional[str]:
        probe_payloads = [
            "/?test=<script>alert(1)</script>",
            "/?id=1' OR '1'='1",
            "/?file=../../../etc/passwd",
        ]

        for payload in probe_payloads:
            url = f"{base_url.rstrip('/')}{payload}"
            resp = await self.client.get(url, retries=1)
            if resp:
                waf = self.detect_waf_from_response(resp.headers, resp.body, resp.status_code)
                if waf:
                    return waf

        return None

    def get_bypass_headers(self, waf: Optional[str] = None) -> dict[str, str]:
        headers: dict[str, str] = {}
        waf_name = waf or self.detected_waf or ""

        bypass_headers = [
            ("X-Forwarded-For", f"127.0.0.1, {_random_ip()}"),
            ("X-Real-IP", "127.0.0.1"),
            ("X-Originating-IP", "127.0.0.1"),
            ("X-Remote-IP", "127.0.0.1"),
            ("X-Remote-Addr", "127.0.0.1"),
            ("X-Client-IP", "127.0.0.1"),
            ("True-Client-IP", "127.0.0.1"),
            ("CF-Connecting-IP", "127.0.0.1"),
            ("X-Custom-IP-Authorization", "127.0.0.1"),
            ("Forwarded", "for=127.0.0.1;proto=http"),
        ]

        selected = random.sample(bypass_headers, min(3, len(bypass_headers)))
        for k, v in selected:
            headers[k] = v

        if "cloudflare" in waf_name.lower():
            headers["CF-Connecting-IP"] = "127.0.0.1"
            headers["CF-Visitor"] = '{"scheme":"https"}'

        return headers

    def encode_url_bypass(self, path: str, technique: str = "random") -> str:
        techniques = ["double_encode", "unicode", "mixed", "path_traversal", "case"]
        if technique == "random":
            technique = random.choice(techniques)

        if technique == "double_encode":
            encoded = urllib.parse.quote(path, safe="/")
            return urllib.parse.quote(encoded, safe="/")

        elif technique == "unicode":
            result = ""
            for c in path:
                if c.isalpha() and random.random() < 0.3:
                    result += f"%u{ord(c):04x}"
                else:
                    result += c
            return result

        elif technique == "mixed":
            result = ""
            for c in path:
                if c.isalpha() and random.random() < 0.4:
                    result += urllib.parse.quote(c)
                else:
                    result += c
            return result

        elif technique == "path_traversal":
            parts = path.split("/")
            obfuscated = []
            for i, part in enumerate(parts):
                obfuscated.append(part)
                if i > 0 and random.random() < 0.2:
                    obfuscated.append(".")
            return "/".join(obfuscated)

        elif technique == "case":
            return "".join(c.upper() if random.random() > 0.5 else c.lower() for c in path)

        return path

    def get_bypass_content_types(self) -> list[str]:
        return [
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data",
            "text/xml",
            "application/xml",
            "text/plain",
            "application/json;charset=utf-8",
            "application/json; charset=UTF-8",
            "Application/JSON",
            "application/x-json",
        ]

    async def try_bypass_request(
        self,
        url: str,
        payload: str,
        param: str = "id",
        method: str = "GET",
    ) -> list[dict]:
        results = []
        bypass_methods = self._get_bypass_methods(url, payload, param)

        for method_name, kwargs in bypass_methods:
            resp = await self.client.request(method, url, retries=1, **kwargs)
            if resp and resp.status_code not in (403, 406, 429, 503):
                results.append({
                    "bypass_method": method_name,
                    "url": url,
                    "status": resp.status_code,
                    "response_length": len(resp.body),
                    "payload": payload,
                })
                break

        return results

    def _get_bypass_methods(self, url: str, payload: str, param: str) -> list[tuple[str, dict]]:
        methods: list[tuple[str, dict]] = []

        methods.append(("double_url_encode", {
            "params": {param: urllib.parse.quote(urllib.parse.quote(payload))},
        }))

        methods.append(("unicode_encode", {
            "params": {param: _unicode_encode(payload)},
        }))

        methods.append(("comment_injection_sql", {
            "params": {param: payload.replace(" ", "/**/")},
        }))

        methods.append(("case_variation", {
            "params": {param: _case_vary(payload)},
        }))

        methods.append(("content_type_json", {
            "json_data": {param: payload},
            "extra_headers": {"Content-Type": "application/json"},
        }))

        methods.append(("method_override", {
            "params": {param: payload},
            "extra_headers": {"X-HTTP-Method-Override": "GET"},
        }))

        methods.append(("chunked_transfer", {
            "params": {param: payload},
            "extra_headers": {"Transfer-Encoding": "chunked"},
        }))

        methods.append(("multipart_bypass", {
            "data": {param: payload},
            "extra_headers": {"Content-Type": "multipart/form-data; boundary=----PhantomBoundary"},
        }))

        return methods

    async def scan_with_bypass(self, base_url: str) -> list[Finding]:
        findings: list[Finding] = []

        waf = await self.detect_waf(base_url)
        if waf:
            findings.append(Finding(
                url=base_url,
                title=f"WAF Detected: {waf}",
                severity=Severity.INFO,
                module=ScanModule.VULNS,
                description=f"A Web Application Firewall ({waf}) was detected protecting this target.",
                evidence=f"WAF fingerprinted as: {waf}",
                recommendation="Document WAF type for bypass testing. Note: WAF presence doesn't mean the application is secure.",
            ))

            bypass_headers = self.get_bypass_headers(waf)
            test_resp = await self.client.get(
                base_url,
                extra_headers=bypass_headers,
                retries=1,
            )

            if test_resp and test_resp.status_code not in (403, 503):
                findings.append(Finding(
                    url=base_url,
                    title=f"WAF Bypass Possible via IP Spoofing Headers ({waf})",
                    severity=Severity.HIGH,
                    module=ScanModule.VULNS,
                    description=f"The {waf} WAF may be bypassable by spoofing IP forwarding headers (X-Forwarded-For, CF-Connecting-IP, etc.).",
                    evidence=f"Request with spoofed headers returned HTTP {test_resp.status_code}",
                    recommendation="Configure WAF to not trust X-Forwarded-For headers from untrusted sources. Validate real IP at network level.",
                ))

        return findings


def _random_ip() -> str:
    return f"{random.randint(1,254)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"


def _unicode_encode(s: str) -> str:
    result = ""
    for c in s:
        if c.isalpha() and random.random() < 0.4:
            result += f"\\u{ord(c):04x}"
        else:
            result += c
    return result


def _case_vary(s: str) -> str:
    result = ""
    for c in s:
        if c.isalpha():
            result += c.upper() if random.random() > 0.5 else c.lower()
        else:
            result += c
    return result
